from enum import Enum


class UserRole(str, Enum):
    USER = "user"
    SUPERUSER = "superuser"


URL_LENGTH = 255

USER_NAME_LENGTH = 255
USER_EMAIL_LENGTH = 255
USER_HASHED_PASSWORD_LENGTH = 60

WISH_TITLE_LENGTH = 255
WISH_DESCRIPTION_LENGTH = 2048
WISH_PRICE_PRECISION = 10
WISH_PRICE_SCALE = 2

WISHLIST_TITLE_LENGTH = 255
WISHLIST_DESCRIPTION_LENGTH = 2048
